### ISSUE TITLE
Lisence fix

### ISSUE THREAD

**Issue by pernydev** [Calemi/PlayingCards-1.16.4#16]
Hey! I'm aware that this project is abandoned. But if possible, could you please fix the lisence? This project is not forge nor a library so it probably shouldn't be lisenced under LGPL. 

I am requesting this because of my interest to fork the project! 

Thank you!

**Comment by Chemmaster73** [comment]
If you update it to 1.20.1 please send it to me! I have a small server with my friends and we would lobe to use this mod. We use Forge.

**Comment by pernydev** [comment]
> If you update it to 1.20.1 please send it to me! I have a small server with my friends and we would lobe to use this mod. We use Forge.
> 

I would love to fork it, it's just that I don't know if I can. They are clearly using the wrong lisence (one meant for libraries, not software)

**Comment by Calemi** [comment]
License should be fixed
